// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1hXZvzt_EA5Qaw35DNZiqBD0QVE2cZmU',
    appId: '1:276973196207:web:73ce6607b4147ebe5f155a',
    messagingSenderId: '276973196207',
    projectId: 'privyr-w13',
    authDomain: 'privyr-w13.firebaseapp.com',
    storageBucket: 'privyr-w13.appspot.com',
    measurementId: 'G-W68ZRCLHRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI8f0T3Ku9AV15RLcTMMF0Zqea4bowe6Y',
    appId: '1:276973196207:android:c768653e0eb59b6c5f155a',
    messagingSenderId: '276973196207',
    projectId: 'privyr-w13',
    storageBucket: 'privyr-w13.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyX4VTSTrMsvuGayowNe7znV8DA85ehG0',
    appId: '1:276973196207:ios:66bfdf1fb2b6f7d15f155a',
    messagingSenderId: '276973196207',
    projectId: 'privyr-w13',
    storageBucket: 'privyr-w13.appspot.com',
    iosBundleId: 'com.example.privyr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1hXZvzt_EA5Qaw35DNZiqBD0QVE2cZmU',
    appId: '1:276973196207:web:a6e037a65a903e055f155a',
    messagingSenderId: '276973196207',
    projectId: 'privyr-w13',
    authDomain: 'privyr-w13.firebaseapp.com',
    storageBucket: 'privyr-w13.appspot.com',
    measurementId: 'G-RKEBHWN5GD',
  );
}
